import { defineDict } from '../index';

export const legalAnalysis = defineDict({
  es: {
    analyze: 'Analizar',
    stop: 'Detener',
    running: 'Analizando…',
    stopping: 'Deteniendo…',
    retry: 'Reintentar',
    dismiss: 'Descartar',
    loadError: 'No se pudo cargar el análisis.',
    emptyTitle: 'Sin análisis todavía',
    emptyDescription:
      'Ejecutá el análisis adversarial para ver la defensa, el ataque simulado, la postura del juez y los riesgos.',
    defenseTitle: 'Defensa',
    attackTitle: 'Ataque de la contraparte',
    judgeTitle: 'Postura del juez',
    riskTitle: 'Riesgos',
    questionsTitle: 'Preguntas abiertas',
    synthesisTitle: 'Síntesis',
    attackSimulation: 'Simulación interna — no presentable',
    attackSimulationHint:
      'El ataque lo genera el propio sistema como ejercicio interno de contraste. No es un escrito rival ni material presentable.',
    incompleteWarning: 'Análisis incompleto: {done} de 4 personas',
    counters: '{verified} verificadas · {unverified} sin verificar',
    confidence: 'Confianza: {value} %',
    strength: 'Solidez: {value}',
    strengthHigh: 'alta',
    strengthMedium: 'media',
    strengthLow: 'baja',
    leaning: 'Tendencia: {value}',
    leaningFavorable: 'favorable',
    leaningUnfavorable: 'desfavorable',
    leaningUnclear: 'indefinida',
    verifiedBadge: 'verificada',
    unverifiedBadge: 'sin verificar',
    noBasis: 'Sin fundamento citado.',
    noItems: 'Sin elementos.',
    noSynthesis: 'Sin síntesis disponible.',
  },
  en: {
    analyze: 'Analyze',
    stop: 'Stop',
    running: 'Analyzing…',
    stopping: 'Stopping…',
    retry: 'Retry',
    dismiss: 'Dismiss',
    loadError: 'Could not load the analysis.',
    emptyTitle: 'No analysis yet',
    emptyDescription:
      'Run the adversarial analysis to see the defense, the simulated attack, the judge posture and the risks.',
    defenseTitle: 'Defense',
    attackTitle: 'Opposing attack',
    judgeTitle: 'Judge posture',
    riskTitle: 'Risks',
    questionsTitle: 'Open questions',
    synthesisTitle: 'Synthesis',
    attackSimulation: 'Internal simulation — not for filing',
    attackSimulationHint:
      'The attack is generated by the system itself as an internal contrast exercise. It is not rival briefing nor presentable material.',
    incompleteWarning: 'Incomplete analysis: {done} of 4 personas',
    counters: '{verified} verified · {unverified} unverified',
    confidence: 'Confidence: {value} %',
    strength: 'Strength: {value}',
    strengthHigh: 'high',
    strengthMedium: 'medium',
    strengthLow: 'low',
    leaning: 'Leaning: {value}',
    leaningFavorable: 'favorable',
    leaningUnfavorable: 'unfavorable',
    leaningUnclear: 'unclear',
    verifiedBadge: 'verified',
    unverifiedBadge: 'unverified',
    noBasis: 'No cited basis.',
    noItems: 'No items.',
    noSynthesis: 'No synthesis available.',
  },
});

export type LegalAnalysisMessages = (typeof legalAnalysis)['es'];

declare module '../types' {
  interface I18nSchema {
    legalAnalysis: LegalAnalysisMessages;
  }
}
