export {
  Brain,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleStop,
  Copy,
  Download,
  Ellipsis,
  ExternalLink,
  Globe,
  Info,
  LoaderCircle,
  Menu,
  MessageSquare,
  Mic,
  Moon,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Sparkles,
  Square,
  Sun,
  Trash,
  TriangleAlert,
  Upload,
  X,
} from 'lucide-react';

export type { LucideIcon } from 'lucide-react';

// Alias de compatibilidad: lucide-react 1.x renombró estos iconos.
export {
  CircleAlert as AlertCircle,
  CircleStop as StopCircle,
  Ellipsis as MoreHorizontal,
  LoaderCircle as Loader2,
  Trash as Trash2,
} from 'lucide-react';
